version: '3'

tasks:
  format:
    cmds:
    - deno fmt README.md
    - gofmt -w .
  lint: golangci-lint run --fix --timeout "10m"
  test: go run github.com/onsi/ginkgo/v2/ginkgo -tags fts5 -cover -race -r
  server: go run -tags fts5 loge/main.go --port 6500 --payload-size 100000 --buckets 2
  proto:
    desc: Generate protobuf Go code
    cmds:
    - protoc --go_out=. --go_opt=paths=source_relative proto/payload.proto
    sources:
    - proto/*.proto
    generates:
    - proto/*.pb.go
  default:
    cmds:
    - GOFLAGS='-mod=mod' go generate ./...
    - task: format
    - task: lint
    - task: test
  bench:
    desc: Run benchmarks (starts server, runs k6 tests, then stops server)
    cmds:
    - rm -Rf tmp/
    - go test -tags fts5 -bench=. -benchmem -run ^$
    - go build -tags fts5 -o /tmp/loge-bench ./loge/main.go
    - |
      # Function to start server and wait for it to be ready
      start_server() {
        rm -Rf tmp/
        /tmp/loge-bench --port 6500 --payload-size 100000 --buckets 2 &
        SERVER_PID=$!
        echo "Started server with PID $SERVER_PID"
        
        echo "Waiting for server to be ready..."
        for i in $(seq 1 30); do
          if nc -z localhost 6500 2>/dev/null; then
            echo "Server is ready!"
            return 0
          fi
          if [ $i -eq 30 ]; then
            echo "Server failed to start within 30 seconds"
            return 1
          fi
          sleep 1
        done
      }
      
      # Function to stop server and wait for graceful shutdown (flushes backpressure)
      stop_server() {
        if [ -n "$SERVER_PID" ]; then
          echo "Stopping server (PID $SERVER_PID) and waiting for flush..."
          kill -TERM $SERVER_PID 2>/dev/null || true
          # Wait for graceful shutdown (server flushes all pending data)
          wait $SERVER_PID 2>/dev/null || true
          echo "Server stopped and flushed."
          sleep 1
        fi
        SERVER_PID=""
      }
      
      # Cleanup on exit
      trap stop_server EXIT
      
      # Run msgpack benchmark
      echo ""
      echo "=========================================="
      echo "Running msgpack benchmark..."
      echo "=========================================="
      start_server || exit 1
      k6 run benchmark/streams.msgpack.js
      stop_server
      
      # Run JSON benchmark
      echo ""
      echo "=========================================="
      echo "Running JSON benchmark..."
      echo "=========================================="
      start_server || exit 1
      k6 run benchmark/streams.json.js
      stop_server
      
      # Run protobuf benchmark
      echo ""
      echo "=========================================="
      echo "Running protobuf benchmark..."
      echo "=========================================="
      start_server || exit 1
      k6 run benchmark/streams.protobuf.js
      stop_server
      
      echo ""
      echo "All benchmarks complete!"