version: '3'

tasks:
  format:
    cmds:
    - deno fmt README.md
    - gofmt -w .
  lint: golangci-lint run --fix --timeout "10m"
  test: go run github.com/onsi/ginkgo/v2/ginkgo -tags fts5 -cover -race -r
  default:
    cmds:
    - go generate ./...
    - task: format
    - task: lint
    - task: test
  bench:
    cmds:
    - go test -tags fts5 -bench=. -benchmem -run ^$
    - k6 run benchmark/streams.msgpack.js
    - k6 run benchmark/streams.json.js