// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/payload.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamEntry         `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_proto_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_proto_payload_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetStreams() []*StreamEntry {
	if x != nil {
		return x.Streams
	}
	return nil
}

type StreamEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        map[string]string      `protobuf:"bytes,1,rep,name=stream,proto3" json:"stream,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Values        []*Value               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEntry) Reset() {
	*x = StreamEntry{}
	mi := &file_proto_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEntry) ProtoMessage() {}

func (x *StreamEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEntry.ProtoReflect.Descriptor instead.
func (*StreamEntry) Descriptor() ([]byte, []int) {
	return file_proto_payload_proto_rawDescGZIP(), []int{1}
}

func (x *StreamEntry) GetStream() map[string]string {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *StreamEntry) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_payload_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Value) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_proto_payload_proto protoreflect.FileDescriptor

const file_proto_payload_proto_rawDesc = "" +
	"\n" +
	"\x13proto/payload.proto\x12\x04loge\"6\n" +
	"\aPayload\x12+\n" +
	"\astreams\x18\x01 \x03(\v2\x11.loge.StreamEntryR\astreams\"\xa4\x01\n" +
	"\vStreamEntry\x125\n" +
	"\x06stream\x18\x01 \x03(\v2\x1d.loge.StreamEntry.StreamEntryR\x06stream\x12#\n" +
	"\x06values\x18\x02 \x03(\v2\v.loge.ValueR\x06values\x1a9\n" +
	"\vStreamEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x05Value\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04lineB Z\x1egithub.com/jtarchie/loge/protob\x06proto3"

var (
	file_proto_payload_proto_rawDescOnce sync.Once
	file_proto_payload_proto_rawDescData []byte
)

func file_proto_payload_proto_rawDescGZIP() []byte {
	file_proto_payload_proto_rawDescOnce.Do(func() {
		file_proto_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payload_proto_rawDesc), len(file_proto_payload_proto_rawDesc)))
	})
	return file_proto_payload_proto_rawDescData
}

var file_proto_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_payload_proto_goTypes = []any{
	(*Payload)(nil),     // 0: loge.Payload
	(*StreamEntry)(nil), // 1: loge.StreamEntry
	(*Value)(nil),       // 2: loge.Value
	nil,                 // 3: loge.StreamEntry.StreamEntry
}
var file_proto_payload_proto_depIdxs = []int32{
	1, // 0: loge.Payload.streams:type_name -> loge.StreamEntry
	3, // 1: loge.StreamEntry.stream:type_name -> loge.StreamEntry.StreamEntry
	2, // 2: loge.StreamEntry.values:type_name -> loge.Value
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_payload_proto_init() }
func file_proto_payload_proto_init() {
	if File_proto_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payload_proto_rawDesc), len(file_proto_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_payload_proto_goTypes,
		DependencyIndexes: file_proto_payload_proto_depIdxs,
		MessageInfos:      file_proto_payload_proto_msgTypes,
	}.Build()
	File_proto_payload_proto = out.File
	file_proto_payload_proto_goTypes = nil
	file_proto_payload_proto_depIdxs = nil
}
